[package]
name = "having_fun"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.9.3"
anyhow = "1.0.79"
ahash = "0.8.7"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false